version: '3.7'

services:
  postgresql:
    image: bitnami/postgresql:10
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - sonarqube
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

  sonarqube:
    image: bitnami/sonarqube:7
    depends_on:
      - postgresql
    environment:
      POSTGRESQL_HOST: postgresql
      POSTGRESQL_ROOT_USER: postgres
      POSTGRESQL_CLIENT_CREATE_DATABASE_NAME: bitnami_sonarqube
      POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME: bn_sonarqube
      POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD: bitnami1234
      SONARQUBE_DATABASE_NAME: bitnami_sonarqube
      SONARQUBE_DATABASE_USER: bn_sonarqube
      SONARQUBE_DATABASE_PASSWORD: bitnami1234
      SONARQUBE_USERNAME: Dav97
      SONARQUBE_PASSWORD: daviddavid
    ports:
      - 80:9000  
    volumes:
      - sonarqube_data:/bitnami
    networks:
      - sonarqube
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:  
          - node.role==manager
      restart_policy:
        condition: on-failure

volumes:
  sonarqube_data: {}
  postgresql_data: {}

networks:
  sonarqube: